$usbd = get-wmiobject -Class Win32_Volume | where{$_.Label -eq 'ENDER3'}
Write-Host ("Copying firmware to " + $usbd.DriveLetter)
copy .\.pio\build\STM32F103RE_btt_USB\firmware.bin $usbd.DriveLetter
Write-Host ("Ejecting " + $usbd.DriveLetter)
$driveEject = New-Object -comObject Shell.Application
$driveEject.Namespace(17).ParseName($usbd.DriveLetter).InvokeVerb("Eject")



# SIG # Begin signature block
# MIIFlAYJKoZIhvcNAQcCoIIFhTCCBYECAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU8ImfzasH9SdmNWM+aUtRqWWk
# CY2gggMiMIIDHjCCAgagAwIBAgIQO40FGM38HIpJNC89XRx3rzANBgkqhkiG9w0B
# AQsFADAnMSUwIwYDVQQDDBxQb3dlclNoZWxsIENvZGUgU2lnbmluZyBDZXJ0MB4X
# DTIxMTAyNDE5MTU1OVoXDTIyMTAyNDE5MzU1OVowJzElMCMGA1UEAwwcUG93ZXJT
# aGVsbCBDb2RlIFNpZ25pbmcgQ2VydDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
# AQoCggEBAMv5EtAtenAzc/bIBmIARHABvDVmjFbwXL7P/Ts4kZajLnmUcRAJzUUa
# xISkH4O6YXeDvN+r4gw9EJGZ3kKQMcgaB4nydlb3FR8RnZAabsJL7nqiU6QxJsf2
# /2e2eEjW1wRHeeOQwX70seAmloMX1pEhjItOgdnLwaZ6BlBI5flFqFWGk76Q5bok
# Vz2QyIGUjxNG0pC6TZ6CcgoRmNLvbZYxiowG2qDjlJaOqbBdgZwtBBGfj+nswgKE
# edKkItevFyugfPt5YFTXhA4rawGbZgWgsO0Uhhit4QWbtdMte8e6kr3FaXdoR6bM
# ZsginJ99HPy+7MG5qa1q8pDWgdsIBpkCAwEAAaNGMEQwDgYDVR0PAQH/BAQDAgeA
# MBMGA1UdJQQMMAoGCCsGAQUFBwMDMB0GA1UdDgQWBBSo0b+4mfrVMma0xksERVbZ
# Ee8opzANBgkqhkiG9w0BAQsFAAOCAQEAvQIQDPf7hM/j4WZhnp0akGW5AEyaH8Qo
# 7HDZV9n3rnPrwWDZKdGAj1NkyxKGid3ITEdnjawXsY1F9cWkJ+eZTggseZ+RqcQM
# Uk1aJRkNUkLvoP8uw6NP6IBdojnXHcpgYk2IUQIr5+BeWEcywDPD31YZE5meSGMs
# oaEb8bZz3r5VjOy9JYRNUUi1fI0596rBiH+3UzJUEWx75qkJNaX0i63M/XRo+s0A
# feLAVO38DwJg6G89Bn/AfdHy0b4I55/RhB5d98nyiOzxNXZnSuMjXm/JkNJb7xNQ
# UZvvxET9EoZw5cuAfgifbllDgxsX9lPt0vVlSKYkFp0tKcmM70ojeTGCAdwwggHY
# AgEBMDswJzElMCMGA1UEAwwcUG93ZXJTaGVsbCBDb2RlIFNpZ25pbmcgQ2VydAIQ
# O40FGM38HIpJNC89XRx3rzAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAig
# AoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgEL
# MQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQUnVzqW+xg3+00wXzxXujo
# 3AaFnaMwDQYJKoZIhvcNAQEBBQAEggEAOcn2oMGM0KaQ1S1euVZ84kRbc08CrIu5
# dO7h45xBpMGxfq/9pMPO7dOKyjOxgPs8Bjh2ipDjsMHfT5w/cMRS90s3XTMm4KY7
# 68f2mijaLmwrZqXJMXjgbYQSRy/sTEPYR1vTx+FKOUwXt2kDqLuLwx2AVtHjw0iZ
# dYuJkPWHI5Ejlm3u4XfOSB4PUIqKH9/1VYK+hjFqh4jIBMKWLbP4xJGDOpVvKR3A
# 9NZJieqUNNTF1aB3jy0BDsBzLHRinlma3YAtLKSv70YkwBdBWAzvBBEnpsWtbXvc
# PKwsXihWVwakPB0lwjKdEvyQ69FTELI8fPVzzYI9Zhfe2g9Lv8598A==
# SIG # End signature block
